<?php
$translations = [
    'pt' => [
        'title' => "Refino Albion",
        'titulo' => "Selecione o Tipo de Refino",
        'titulopelego' => "Calculadora de Refino - Pelegos",
        'titulotecido' => "Calculadora de Refino - Fibras",
        'minerio' => "Refino de Minério",
        'pelego' => "Refino de Pelego",
        'tecido' => "Refino de Tecido",
        'madeira' => "Refino de Madeira",
        'pedra' => "Refino de Pedra",
        'outros' => "Outros Refinos",
        'mineriodesc' => "Calculadora para refino de metais e barras",
        'pelegodesc' => "Calculadora para refino de couros e pelegos",
        'tecidodesc' => "Calculadora para refino de fibras e tecidos",
        'madeiradesc' => "Calculadora para refino de madeiras e tábuas",
        'pedradesc' => "Calculadora para refino de pedras e blocos",
        'outrosdesc' => "Calculadora para outros refinos",
        'copyright' => "© 2025 Calculadora de Refino - Albion Online. Todos os direitos reservados.",
        'form_tier' => "Tier",
        'form_encantamento' => "Encantamento",
        'form_cidadeCompraFibra' => "Cidade de Compra (Fibra)",
        'form_cidadeCompraPelego' => "Cidade de Compra (Pelego)",
        'form_cidadeVendaTecido' => "Cidade de Venda (Tecido)",
        'form_cidadeVendaCouro' => "Cidade de Venda (Couro)",
        'form_quantidade' => "Quantidade",
        'form_taxaImposto' => "Taxa de Imposto (Fee)",
        'form_taxaRetorno' => "Taxa de Retorno (%)",
        'form_calcular' => "Calcular"
    ],
    'en' => [
        'title' => "Albion Refinement",
        'titulo' => "Select Refining Type",
        'titulopelego' => "Refining Calculator - Leathers",
        'titulotecido' => "Refining Calculator - Fibers",
        'minerio' => "Ore Refining",
        'pelego' => "Leather Refining",
        'tecido' => "Cloth Refining",
        'madeira' => "Wood Refining",
        'pedra' => "Stone Refining",
        'outros' => "Other Refinements",
        'mineriodesc' => "Calculator for refining metals and bars",
        'pelegodesc' => "Calculator for refining leather and hides",
        'tecidodesc' => "Calculator for refining fibers and clothes",
        'madeiradesc' => "Calculator for refining wood and boards",
        'pedradesc' => "Calculator for stone and blocks",
        'outrosdesc' => "Other Refinements",
        'copyright' => "© 2025 Refining Calculator - Albion Online. All rights reserved.",
        'form_tier' => "Tier",
        'form_encantamento' => "Enchantment",
        'form_cidadeCompraFibra' => "Purchase City (Fiber)",
        'form_cidadeCompraPelego' => "Purchase City (Hide)",
        'form_cidadeVendaTecido' => "Sell City (Cloth)",
        'form_cidadeVendaCouro' => "Sell City (Leather)",
        'form_quantidade' => "Amount",
        'form_taxaImposto' => "Tax (Fee)",
        'form_taxaRetorno' => "Return Rate (%)",
        'form_calcular' => "Calculate"
    ],
    'es' => [
        'title' => "Refinamiento de Albion",
        'titulo' => "Seleccionar el tipo de refinación",
        'titulopelego' => "Calculadora de refinación - Cuero",
        'titulotecido' => "Calculadora de refinación - Fibras",
        'minerio' => "Refinación de minerales",
        'pelego' => "Refinación del cuero",
        'tecido' => "Refinación de tejidos",
        'madeira' => "Refinación de madera",
        'pedra' => "Refinación de piedras",
        'outros' => "Otros refinamientos",
        'mineriodesc' => "Calculadora para refinar metales y barras",
        'pelegodesc' => "Calculadora para refinar cueros y pieles",
        'tecidodesc' => "Calculadora para refinar fibras y tejidos",
        'madeiradesc' => "Calculadora para refinar madera y tableros",
        'pedradesc' => "Calculadora de refinación de piedras y bloques",
        'outrosdesc' => "Otros refinamientos",
        'copyright' => "© 2025 Calculadora de refinación - Albion Online. Reservados todos los derechos.",
        'form_tier' => "Tier",
        'form_encantamento' => "Encantamiento",
        'form_cidadeCompraFibra' => "Ciudad de Compra (Fibra)",
        'form_cidadeCompraPelego' => "Ciudad de Compra (Piel)",
        'form_cidadeVendaTecido' => "Ciudad de Venta (Tejido)",
        'form_cidadeVendaCouro' => "Ciudad de Venta (Cuero)",
        'form_quantidade' => "Cantidad",
        'form_taxaImposto' => "Tasa de Impuesto (Fee)",
        'form_taxaRetorno' => "Tasa de Retorno (%)",
        'form_calcular' => "Calcular"
    ],
];

$lang = $_SESSION['lang'] ?? $_GET['lang'] ?? 'pt'; // Padrão para 'pt'
if (!isset($translations[$lang])) {
    $lang = 'pt'; // Fallback para o padrão se o idioma selecionado não existir
}
$_SESSION['lang'] = $lang; // Armazena a preferência

$txt = $translations[$lang]; //
?>